In [42]:
import os
path = os.getcwd()
path 

'C:\\Python_Projects\\Tutorials'

In [43]:
newpath = 'C:\\Python_Projects\\'

In [1]:
os.mkdir(newpath + "\\Priyanka")

NameError: name 'os' is not defined

In [6]:
from numpy import *


In [7]:
arr = linspace(1,5,3)

In [8]:
arr

array([1., 3., 5.])

In [9]:
arr=logspace(1,10,8)

In [10]:
arr

array([1.00000000e+01, 1.93069773e+02, 3.72759372e+03, 7.19685673e+04,
       1.38949549e+06, 2.68269580e+07, 5.17947468e+08, 1.00000000e+10])

In [11]:
arr=arange(1,15,2)

In [12]:
arr

array([ 1,  3,  5,  7,  9, 11, 13])

In [13]:
arr = array([1,2,3,4])

In [14]:
arr

array([1, 2, 3, 4])

In [15]:
arr = ones(5)

In [16]:
arr

array([1., 1., 1., 1., 1.])

In [17]:
arr = zeros(5)

In [18]:
arr

array([0., 0., 0., 0., 0.])

In [19]:
arr = array([1,2,3,4])
arr = arr + 5

In [20]:
arr

array([6, 7, 8, 9])

In [21]:
arr = array([1,2,3,4])
print(sin(arr))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [22]:
print(sqrt(arr))

[1.         1.41421356 1.73205081 2.        ]


In [27]:
arr1 = array([1,5,4,6])
arr2 = array([9,11,7,10])
print(concatenate([arr1,arr2]))

[ 1  5  4  6  9 11  7 10]


In [29]:
arr1 = array([1,5,4,6])
arr2 = arr1
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))

[1 5 4 6]
[1 5 4 6]
2388204269712
2388204269712


In [30]:
arr1 = array([1,5,4,6])
arr2 = arr1.view()
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))

[1 5 4 6]
[1 5 4 6]
2388222671824
2388213879216


In [31]:
#shallow copy
arr1 = array([1,5,4,6])
arr2 = arr1.view()
arr1[1]=88
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))

[ 1 88  4  6]
[ 1 88  4  6]
2388222670672
2388222569424


In [32]:
#deep copy
arr1 = array([1,5,4,6])
arr2 = arr1.copy()
arr1[1]=88
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))

[ 1 88  4  6]
[1 5 4 6]
2388207336496
2388207334672


In [35]:
arr1 = array([2, 6, 8, 9, 1])
arr2 = array([1, 2, 3, 4, 5])
list1 = [ ] 
e = 0
for num1 in arr1:
      list1.append(arr2[e] + num1)
      e+=1

print(array(list1))

[ 3  8 11 13  6]


In [51]:
Students = ["Ishu1","Priyu2","Jids3","Bhakti4", "Aastha5"]
absent_Student = ["Jids3", "Aastha5"]

In [52]:
import os
path = os.getcwd()
path
for student in Students:
    new_path = path + f"\\{student}"
    if student not in absent_Student:
        print(new_path)
        os.mkdir(new_path)

C:\Python_Projects\Tutorials\Ishu1
C:\Python_Projects\Tutorials\Priyu2
C:\Python_Projects\Tutorials\Bhakti4
